### ISSUE TITLE
Routing not working in development

### ISSUE THREAD

**Issue by reallifenero** [MathisHumbert/fleava-production-clone#1]
- Cloned the repository to test in development
- Application does not route to`about`  or `works/detail` pages when navigaion is initiated.
- Any workaround to `vite.config.js` rollup options ?

**Tagging** for faster response @MathisHumbert

**Comment by MathisHumbert** [comment]
This project is outdated, i would recommend to have a look at my latest repository

**Comment by reallifenero** [comment]
Alright. 

Would appreciate if you tag it so I don't pick the wrong vite project.
